#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

RE_VERSION="1.0.0"
RE_SOURCE_FILE_PATH="${HOME}/.remotes"
RE_NUMBER=""

# prints the help message
print_usage() {
    echo -e "
usage: remotes [<option> ... | <remote-number>]

OPTIONS:

  $(bold "-l | --list")      List the remotes
  $(bold "-e | --edit")      Edit the remotes source file
  $(bold "-h | --help")      Print this help text and exit
  $(bold "-v | --version")   Print the version and exit
    "
}

# print the given message and exits
die() {
    echo -e "${*}" && exit 0
}

bold() {
    echo -e "\033[1m${1}\033[0m"
}

# reads the lines from the remotes file
read_lines() {
    if [[ -f "${RE_SOURCE_FILE_PATH}" ]]; then
        grep -o '^[^#]*' "${RE_SOURCE_FILE_PATH}"
    else
        die "File ${RE_SOURCE_FILE_PATH} not existing."
    fi
}

read_line_from_number() {
    read_lines | sed -n "${1}p"
}

# prints the version and exits
print_version() {
    echo "remotes version ${RE_VERSION}"
}

# edit the source remotes files
edit_source_file() {
    if [[ ! "$(which code)" == "" ]]; then
        (code "${RE_SOURCE_FILE_PATH}" && exit 0)
    elif [[ ! "$(which vim)" == "" ]]; then
        (vim "${RE_SOURCE_FILE_PATH}" && exit 0)
    fi
}

# lists all remotes
list() {
    echo
    RE_LINES=$(read_lines)
    RE_NUMBER=1
    for line in $RE_LINES; do

        RE_USER=$(echo "$line" | rev | cut -d"@" -f2- | rev)
        RE_HOST=$(echo "$line" | rev | cut -d"@" -f1 | rev)

        echo -e "$(bold "${RE_NUMBER}")  ${RE_USER}@$(bold "${RE_HOST}")"
        RE_NUMBER=$((RE_NUMBER + 1))
    done
    echo
}

connect_to_remote() {
    if [[ ! "${1}" =~ ^[0-9]+$ ]]; then
        die "Invalid number: ${1}"
    fi

    RE_REMOTE=$(read_line_from_number "${1}")

    if [[ "${RE_REMOTE}" == "" ]]; then
        die "Invalid number: ${1}"
    fi

    echo && echo "ssh ${RE_REMOTE}" && echo

    ssh "${RE_REMOTE}"

    exit 0
}

# connect to remote
connect_interactive() {
    list
    read -r -p "Enter the number to connect to / $(bold "q") to quit: " RE_ANSWERE

    if [[ "${RE_ANSWERE}" == "q" ]]; then
        exit 0
    else
        connect_to_remote "${RE_ANSWERE}"
    fi
}

# guard existence of argument / command
[[ $# -ne 0 ]] || connect_interactive

while (($# > 0)); do
    opt="${1}"
    shift

    case $opt in
    --list | -l)
        list
        exit 0
        ;;
    --edit | -e)
        edit_source_file
        exit 0
        ;;
    --help | -h)
        print_usage
        exit 0
        ;;
    --version | -v)
        print_version
        exit 0
        ;;
    '' | *[!0-9]*)
        die "Unknown option: '${opt}'.  Pass '$(bold "--help")' for a list of commands."
        ;;
    *)
        RE_NUMBER="${opt}"
        ;;
    esac
done

if [[ "${RE_NUMBER}" == "" ]]; then
    die "no number specified"
else
    connect_to_remote "${RE_NUMBER}"
fi

# clean exit
exit 0
